/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javamysql.ui;

import games.action.*;
import games.adventure.*;
import games.online.*;
import games.card.*;
import games.racing.*;
import java.awt.PopupMenu;

/**
 *
 * @author Taz
 */

public class userpanel extends javax.swing.JFrame {

    private PopupMenu card;
    private PopupMenu online;
    private PopupMenu racing;
    private PopupMenu action;
    /**
     * Creates new form userpanel
     */
    public userpanel() {
        initComponents();
        setTitle("User Panel");
        
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Action = new javax.swing.JButton();
        Racing = new javax.swing.JButton();
        Online = new javax.swing.JButton();
        Card = new javax.swing.JButton();
        Adventure = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        actionn = new javax.swing.JPanel();
        action1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        adventure = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        race = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        onl = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        cardd = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        cu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(765, 504));
        jPanel1.setMinimumSize(new java.awt.Dimension(765, 504));
        jPanel1.setPreferredSize(new java.awt.Dimension(765, 504));
        jPanel1.setLayout(null);

        jPanel3.setLayout(null);

        Action.setText("Action");
        Action.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionActionPerformed(evt);
            }
        });
        jPanel3.add(Action);
        Action.setBounds(2, 60, 140, 43);

        Racing.setText("Racing");
        Racing.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Racing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RacingActionPerformed(evt);
            }
        });
        jPanel3.add(Racing);
        Racing.setBounds(2, 230, 140, 43);

        Online.setText("Online");
        Online.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineActionPerformed(evt);
            }
        });
        jPanel3.add(Online);
        Online.setBounds(2, 180, 140, 43);

        Card.setText("Card");
        Card.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Card.setMaximumSize(new java.awt.Dimension(57, 21));
        Card.setMinimumSize(new java.awt.Dimension(57, 21));
        Card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardActionPerformed(evt);
            }
        });
        jPanel3.add(Card);
        Card.setBounds(2, 290, 140, 43);

        Adventure.setText("Adventure");
        Adventure.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Adventure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdventureActionPerformed(evt);
            }
        });
        jPanel3.add(Adventure);
        Adventure.setBounds(2, 120, 140, 43);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-13, 0, 140, 360);

        jPanel5.setLayout(new java.awt.CardLayout());

        actionn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                actionnAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        actionn.setLayout(null);

        action1.setText("Action Game 1");
        action1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action1ActionPerformed(evt);
            }
        });
        actionn.add(action1);
        action1.setBounds(0, 0, 199, 340);

        jButton4.setText("Action Game 2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        actionn.add(jButton4);
        jButton4.setBounds(205, 0, 203, 340);

        jButton5.setText("Action Game 3");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        actionn.add(jButton5);
        jButton5.setBounds(418, 0, 200, 340);

        jPanel5.add(actionn, "card2");

        adventure.setLayout(null);

        jButton6.setText("Adventure Game 1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        adventure.add(jButton6);
        jButton6.setBounds(0, 0, 199, 330);

        jButton7.setText("Adventure Game 2");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        adventure.add(jButton7);
        jButton7.setBounds(205, 0, 203, 330);

        jButton8.setText("Adventure Game 3");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        adventure.add(jButton8);
        jButton8.setBounds(418, 0, 200, 330);

        jPanel5.add(adventure, "card3");

        race.setLayout(null);

        jButton9.setText("Racing Game 1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        race.add(jButton9);
        jButton9.setBounds(0, 0, 199, 330);

        jButton10.setText("Racing Game 2");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        race.add(jButton10);
        jButton10.setBounds(205, 0, 203, 330);

        jButton11.setText("Adventure Game 3");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        race.add(jButton11);
        jButton11.setBounds(418, 0, 200, 330);

        jPanel5.add(race, "card4");

        jButton12.setText("Online Game 1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Online Game 2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Adventure Game 3");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout onlLayout = new javax.swing.GroupLayout(onl);
        onl.setLayout(onlLayout);
        onlLayout.setHorizontalGroup(
            onlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlLayout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        onlLayout.setVerticalGroup(
            onlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onlLayout.createSequentialGroup()
                .addGroup(onlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel5.add(onl, "card5");

        cardd.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                carddAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton15.setText("Card Game 1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Card Game 2");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Card Game 3");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carddLayout = new javax.swing.GroupLayout(cardd);
        cardd.setLayout(carddLayout);
        carddLayout.setHorizontalGroup(
            carddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carddLayout.createSequentialGroup()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        carddLayout.setVerticalGroup(
            carddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carddLayout.createSequentialGroup()
                .addGroup(carddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel5.add(cardd, "card6");

        jPanel1.add(jPanel5);
        jPanel5.setBounds(137, 11, 618, 355);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 144, 765, 360);

        jPanel2.setLayout(null);

        jLabel1.setText("Current USer :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 28);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 90, 220, 39);

        jLabel2.setText("Account type :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 50, 90, 20);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setText("User");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(90, 50, 90, 20);

        cu.setEditable(false);
        cu.setBackground(new java.awt.Color(255, 255, 255));
        cu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(cu);
        cu.setBounds(90, 20, 100, 18);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(525, 0, 240, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 520, 150);

        setSize(new java.awt.Dimension(781, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Login a = new Login();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AdventureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdventureActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(adventure);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_AdventureActionPerformed

    private void CardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(cardd);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_CardActionPerformed

    private void OnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(onl);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_OnlineActionPerformed

    private void RacingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RacingActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(race);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_RacingActionPerformed

    private void ActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(actionn);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_ActionActionPerformed

    private void actionnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_actionnAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_actionnAncestorAdded

    private void carddAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_carddAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_carddAncestorAdded

    private void action1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action1ActionPerformed
            acg1 a = new acg1();
             this.dispose();
            a.setVisible(true);
    }//GEN-LAST:event_action1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            acg2 b = new acg2();
             this.dispose();
            b.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            acg3 c = new acg3();
             this.dispose();
            c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        adg1 d = new adg1();
         this.dispose();
        d.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        adg2 e = new adg2();
         this.dispose();
        e.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        adg3 f = new adg3();
         this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       cg1 g = new cg1();
        this.dispose();
        g.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        cg2 h = new cg2();
         this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       cg3 i = new cg3();
        this.dispose();
        i.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        og1 j = new og1();
         this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        og2 k = new og2();
         this.dispose();
        k.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        og3 l = new og3();
         this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        g1 m = new g1();
         this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         this.dispose();
        g2 n = new g2();
        n.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
        g3 o = new g3();
        o.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action;
    private javax.swing.JButton Adventure;
    private javax.swing.JButton Card;
    private javax.swing.JButton Online;
    private javax.swing.JButton Racing;
    private javax.swing.JButton action1;
    private javax.swing.JPanel actionn;
    private javax.swing.JPanel adventure;
    private javax.swing.JPanel cardd;
    public static javax.swing.JTextField cu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel onl;
    private javax.swing.JPanel race;
    // End of variables declaration//GEN-END:variables
}
